### ISSUE TITLE
Spelling error on cookie unset

### ISSUE THREAD

**Issue by AllAstronauts** [CleanTalk/ips4-antispam#20]
Plugin:

public function ctCookiesTest()

`			            $check_srting = trim(\IPS\Settings::i()->ct_access_key);
			            foreach($cookie_test['cookies_names'] as $cookie_name){
			                $check_srting .= isset($_COOKIE[$cookie_name]) ? $_COOKIE[$cookie_name] : '';
			            } unset($cokie_name);`

unset($cokie_name);    // Change to unset($cookie_name);

:)

**Comment by davydovct** [comment]
Hello, 

Thanks, it was fixed here:
https://github.com/CleanTalk/ips4-antispam/commit/566d80da01967f9f677cd514eb09bbf15ecb8680
