### ISSUE TITLE
Error when trying to view notification settings in ACP

### ISSUE THREAD

**Issue by Mythotical** [CleanTalk/ips4-antispam#21]
Anytime I try to view notification settings in the ACP I have the following error:
> Error: Class 'IPS\antispambycleantalk\extensions\core\AdminNotifications\antispambycleantalk' not found (0)
> #0 /system/Dispatcher/Controller.php(90): IPS\core\modules\admin\overview\_notifications->settings()
> #1 /system/Dispatcher/Dispatcher.php(152): IPS\Dispatcher\_Controller->execute()
> #2 /index.php(14): IPS\_Dispatcher->run()
> #3 {main}

That prevents me from doing anything with my notification settings so I either have to uninstall the addon or fix it myself which I don't have time to do right now so I figured reporting it would be easier.

**Comment by davydovct** [comment]
Hello,
Thanks, it was fixed in dev build:
https://github.com/CleanTalk/ips4-antispam/commit/9ad464ec549d60f7d454d252644d3fa59258ddcb

Best regards.
